### ISSUE TITLE
rootPathSuffix does not work anymore

### ISSUE THREAD

**Issue by chrisprobst** [michaelzoidl/babel-root-import#13]
Hi,

current version 3.2.0 breaks on OSX and Ubuntu.

```
"browserify": {
    "transform": [
      "babelify"
    ]
  },
  "babel": {
    "presets": [
      "es2015",
      "react"
    ],
    "plugins": [
      "transform-runtime",
      [
        "babel-root-import",
        {
          "rootPathSuffix": "src"
        }
      ],
      "jsx-control-statements"
    ]
  }
```

Error:

Error: Cannot find module '/home/XXX/.gvm/pkgsets/go1.6rc1/global/src/bitbucket.org/XXX/XXX/clientsrc/web/apps/XXX/app/controllers/connection'

As you can see, the part "clientsrc" is the problem. I'm not sure which version worked, because I did not update for a while, but there is definitely something going on here.

Everything worked fine before, just updated and boom.

EDIT: Just confirmed, 3.1.0 works fine. It's 3.2.0 for sure, which causes the problem.

**Comment by dhruvp** [comment]
I'm seeing the same thing as well!

**Comment by michaelzoidl** [comment]
Thanks guys..
I found the mistake - should be fixed now (Version `3.2.2`, already published on npm)

**Comment by chrisprobst** [comment]
Thanks, Sir. 3.2.2 works for me.

**Comment by michaelzoidl** [comment]
awesome
