### ISSUE TITLE
Support require

### ISSUE THREAD

**Issue by DylanPiercey** [michaelzoidl/babel-root-import#19]
Currently it seems like only import is supported, it'd be nice to have both.

**Comment by michaelzoidl** [comment]
Hi dylan, yea - currently it's not supported, i'm looking forward to add the support - but currently i've a lot of work and not that much time :/ 

Maybe you find time to implement this feature :)

**Comment by michaelzoidl** [comment]
Version 4.0 supports this feature :) 
so, close
