### ISSUE TITLE
tries to install a non-existent package called babel-plugin-babel-root-import via npm

### ISSUE THREAD

**Issue by nicerr** [michaelzoidl/babel-root-import#20]
If I have in .babelrc:
`
   "plugins": [
      "babel-root-import"
    ]
`
it tries to install 'babel-plugin-babel-root-import'. See the attached log and the following terminal output:

`> NODE_ENV=development node server.js

Installing babel-plugin-babel-root-import...
npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/nch/.nvm/versions/node/v6.1.0/bin/node" "/Users/nch/.nvm/versions/node/v6.1.0/bin/npm" "install" "babel-plugin-babel-root-import"
npm ERR! node v6.1.0
npm ERR! npm  v3.9.1
npm ERR! code E404
`
If I take out the plugins and don't use '~/' anywhere it's fine. Also it still runs ok even with the errors.
[npm-debug.log.zip](https://github.com/michaelzoidl/babel-root-import/files/269420/npm-debug.log.zip)

**Comment by michaelzoidl** [comment]
Same issue as #23 .. 
I close this issue, lets discuss in the other 
thx
