### ISSUE TITLE
README example missing brackets

### ISSUE THREAD

**Issue by dramamine** [michaelzoidl/babel-root-import#21]
The README is missing an array and therefore fails if you run as-is. Both the rootPathSuffix and rootPathPrefix need to be updated. Should look like this:

  "plugins": [["babel-root-import", {
      "rootPathSuffix": "src/js"
    }]]

Thanks!
Marten

**Comment by michaelzoidl** [comment]
Mh.. are you sure? 

Thats the current example in the README:
```javascript
  "plugins": [
    ["babel-root-import", {
      "rootPathSuffix": "src/js"
    }]
  ]
```

I don't see any diff to your suggestion - except the plugin-block itself has a linebreak.

If i make both to an one-liner (your snippet and the example from the readme:
```
"plugins": [["babel-root-import",{"rootPathSuffix":"src/js"}]]
"plugins": [["babel-root-import",{"rootPathSuffix":"src/js"}]]
```

No diff...

**Comment by michaelzoidl** [comment]
Ah, sorry dude, i think you've mean the first example.. there was a missing bracket, checkout commit
https://github.com/michaelzoidl/babel-root-import/commit/b2be40d337e36c686d057385710d10fc05af0fed

**Comment by dramamine** [comment]
That'll do it!
