### ISSUE TITLE
eslint mark import as invalid

### ISSUE THREAD

**Issue by yinanfang** [michaelzoidl/babel-root-import#22]
The package is working but could you provide a way to get around flow and ESLint error? They keep saying that the import is invalid

![image](https://cloud.githubusercontent.com/assets/4115566/15635463/b886f3ae-25ac-11e6-94ab-65cafb6e6ab0.png)

**Comment by michaelzoidl** [comment]
Good question.. but that is some ESLint config stuff, i think you can allow this "syntax" in an eslint config.
Take a look, as hot-shortfix you can add `// eslint-disable-line` on the end of the line, that disables the linting for this line - but this is no good solution.. 

If you find something, can you write it here? Then we could add this to the readme.. 
Thanks mate..

**Comment by yinanfang** [comment]
I've created a pull request for the changes that's needed for .eslintrc. This will enable us to only ignore things with `~` which is not common and less likely to affect other stuff. As for Flow, we can ignore a file but I don't know how to ignore a single line with regex.
#24

**Comment by michaelzoidl** [comment]
:) awesome dude, thanks for contributing
