### ISSUE TITLE
Can I add multiple path to babelrc?

### ISSUE THREAD

**Issue by pratiko7** [michaelzoidl/babel-root-import#27]
I have a very nested project and was hoping to establish multiple paths based on prefixes. For example:

`@` equates to `src/common`
`~` equates to `src/views`

So imports like below

```
import A from '@/main';     (gets the file from src/common/)
import B from '~/second';   (gets the file from src/views/)
```

**Comment by michaelzoidl** [comment]
Hm.. good question, did you try this?

**Comment by michaelzoidl** [comment]
Should fixed now :) thx @sheepsteak
