### ISSUE TITLE
Babelify - rootPathSuffix giving error

### ISSUE THREAD

**Issue by mikeebee** [michaelzoidl/babel-root-import#28]
Hi there,

I'm using Browserify with Babelify and setting the plugin there. It seems to be working great but as soon as I add `rootPathSuffix` I get this error...

```
{ [Error: Plugin 1 specified in "base" provided an invalid property of "rootPathSuffix" while parsing file: '[filename_omitted]']
  filename: '[filename_omitted]',
```

This is my Browserify Gulp task...

```
browserify({
    entries: [options.src], // Only need initial file, browserify finds the rest
    transform: [
        ['babelify', {
            ignore: /(libs)|(node_modules)|(plugins)/,
            compact: true,
            presets: ['es2015', 'react'],
            plugins: ['babel-root-import', {
                'rootPathSuffix': 'js/src'
            }]
        }],
        ['envify', {
            'global': true,
            '_': 'purge',
            NODE_ENV: 'production'}
        ]
    ], // We want to convert JSX to normal javascript
    debug: options.development, // Gives us sourcemapping
    cache: {},
    packageCache: {},
    fullPaths: options.development // Requirement of watchify
});
```

I also tried adding the settings to a `.babelrc` file but it did nothing. I feel like I'm making a rookie mistake here! :) Hopefully you can shed some light.

Many thanks

Using `Babelify 7.3.0`

**Comment by mikeebee** [comment]
Ah, apologies. I updated Babelify, moved the settings to `.babelrc` (like you specify) and it worked fine. 

But, unfortunately I've had to revert Babel back to version 5 as the project won't run with Babel 6 (I really tried but I couldn't get IE8 to stop throwing an error, even with ES3 presets. On the plus side, I've managed to your plugin working using version `1.0.1`.

Long shot but would you be able to tell me how to hack it so that I can use `rootPathSuffix` in your earlier version with babel 5 please? it's such a great feature.

**Comment by michaelzoidl** [comment]
Phew.. year - today/tomorrow we will update the tool to the v4.0 .. so i can show you the places where we integrated / where you can update the the old version.. 

:) You can make an fork of this repository and then add this feature to the old version, if it work's i will add this to the README

**Comment by mikeebee** [comment]
Great stuff! Thank you

**Comment by mikeebee** [comment]
Good news! I've managed to update to Babel 6 on this project so I can use the latest version.

**Comment by michaelzoidl** [comment]
Cool :) sounds good... sorry, i forgot to write you about the new version, since a few days it's merged .. but i've to publish it on npm ... maybe i've time today... then you could update to the new version of the plugin.
Can i close this issue then?

**Comment by mikeebee** [comment]
No worries man, thanks!

I'll close the issue.
