### ISSUE TITLE
Breaks in Babel 6

### ISSUE THREAD

**Issue by bpmckee** [michaelzoidl/babel-root-import#3]
After upgrading to babel 6 this plugin throws an error.

```
TypeError: r.Transformer is not a function
    at new n (/MyProject/node_modules/babel-root-import/lib/babel-root-import.js:1:519)
    at i (/MyProject/node_modules/babel-root-import/lib/babel-root-import.js:1:1074)
    at Function.memoisePluginContainer (/MyProject/node_modules/babel-core/lib/transformation/file/options/option-manager.js:129:13)
    at Function.normalisePlugin (/MyProject/node_modules/babel-core/lib/transformation/file/options/option-manager.js:163:32)
    at /MyProject/node_modules/babel-core/lib/transformation/file/options/option-manager.js:199:30
    at Array.map (native)
    at Function.normalisePlugins (/MyProject/node_modules/babel-core/lib/transformation/file/options/option-manager.js:175:20)
    at OptionManager.mergeOptions (/MyProject/node_modules/babel-core/lib/transformation/file/options/option-manager.js:273:36)
    at OptionManager.addConfig (/MyProject/node_modules/babel-core/lib/transformation/file/options/option-manager.js:223:10)
    at OptionManager.findConfigs (/MyProject/node_modules/babel-core/lib/transformation/file/options/option-manager.js:366:16)
```

**Comment by michaelzoidl** [comment]
Should be fixed, i updated the project to the newest babel version.
The reason for this error is: in the new babel they moved everything from the `babel` module to the `babel-core` module.

Check if it's working - if all is fine you can close this issue

**Comment by bpmckee** [comment]
I'm still getting the same error.

**Comment by michaelzoidl** [comment]
Ok found the problems... i've also to update the plugin-api.
This is the part of the plugin which i had to update: (it's already updated)
```javascript
export default function ({ Plugin, types: t }) {
  class BabelRootImport {
    root = global.rootPath || process.cwd()

    constructor() {
        return {
          visitor: {
            ImportDeclaration(node){
              const givenPath = node.source.value;
              if (this.hasTildeInString(givenPath)) {
                node.source.value = this.transformRelativeToRootPath(node.source.value);
              }
              return node;
            }
        }
      }
    }
 /* the rest of the code has no changes */
```

The thing is, i've to update also the testing-env ... and there are also multiple changes - i look forward to update the plugin on the next 1-2 days :)

**Comment by bpmckee** [comment]
I tried to help out but failed.  I struggled forcing babel to load my plugin before theirs.  It seemed to load in the correct order until I made a change that threw caused an error.  After that babel decided to load it's stuff first.  I'd have to do weird things like make ordering changes in my .babelrc for it to fix itself but it wasn't consistent. :(

**Comment by PaddyMann** [comment]
I'm hitting the same issue. Using babel-loader and webpack. Updated babel-loader to latest (6.2.0) and installed babel-root-import fresh today  :o

**Comment by michaelzoidl** [comment]
yay i'm still on it.. 
sorry for the delay :/

**Comment by Guuz** [comment]
I also ran into the same problem. Is there a workaround until there is a real fix?

**Comment by qamil** [comment]
Any updates on this? Can we help?

**Comment by q42jaap** [comment]
I ran into this too! We really love the root import by the way!

**Comment by michaelzoidl** [comment]
Ok guys, sorry for the big delay... today i'm sick so i've time to fix this :)
I've good and bad news:
**Good**
The `babel-root-import` works now with Babel 6, after updating to the version `3.0.0` it should work.

**Bad**
Since the `6.XX.X` version is not supporting custom or extra params in the `.babelrc` i had to remove the feature where you can set a custom `root-path` .. hope they update this soon.

**Comment by q42jaap** [comment]
No big deal here, we waited for this fix before upgrading to babel 6. Thanks for the fix! And get well soon!

**Comment by bpmckee** [comment]
Thanks man!

**Comment by PaddyMann** [comment]
tyvm :)
