### ISSUE TITLE
How can I configure `eslint-plugin-import` to resolve?

### ISSUE THREAD

**Issue by ljharb** [michaelzoidl/babel-root-import#34]
It's very valuable to have eslint-plugin-import checking relative imports. The readme recommends ignoring the prefix - how would I configure things so that the prefix is followed rather than ignored?

**Comment by michaelzoidl** [comment]
Hm.. you mean how to configure the eslint right so you don't have to turn of the import rule?

**Comment by ljharb** [comment]
Exactly. The import rule is crucial for catching import path typos.

**Comment by olalonde** [comment]
Also would like this. eslint-plugin-import allows specifying custom resolvers which must follow this spec: https://github.com/benmosher/eslint-plugin-import/tree/master/resolvers

I think we would have to write a resolver that reads the babelrc config.

**Comment by olalonde** [comment]
There's a [resolver](https://github.com/tleunen/eslint-import-resolver-babel-module-alias) for https://github.com/tleunen/babel-plugin-module-alias which accomplishes something similar to this plugin.

**Comment by olalonde** [comment]
Just wrote a resolver :) https://github.com/olalonde/eslint-import-resolver-babel-root-import

Didn't write tests yet but manually tested in my own code and seems to work fine.

**Comment by michaelzoidl** [comment]
:) So, seem's like this is no issue anymore.. so i close this issue
