### ISSUE TITLE
Not sure if you know, but Webpack solves this already

### ISSUE THREAD

**Issue by stevensacks** [michaelzoidl/babel-root-import#35]
http://xabikos.com/2015/10/03/Webpack-aliases-and-relative-paths/

And there's no issues with ESLint on the folder paths. :)

**Comment by michaelzoidl** [comment]
Oh nice, didn't know that, would be great if we have some hint in the README for this case, do you want to make some PR with an updated README? :) Would be awesome 

thx michael

**Comment by stevensacks** [comment]
Sorry, I meant that this package is unnecessary because webpack has built-in functionality to achieve the same thing. I used this package until I discovered the the above link.

**Comment by michaelzoidl** [comment]
Ok, i noted this webpack feature in the readme. thanks for the info... 
https://github.com/michaelzoidl/babel-root-import#fyi
