### ISSUE TITLE
Support re-export syntax

### ISSUE THREAD

**Issue by olalonde** [michaelzoidl/babel-root-import#36]
This plugin doesn't seem to handle `export * from '@/somemodule'` syntax. I believe we would need to duplicate [this code](https://github.com/michaelzoidl/babel-root-import/blob/master/plugin/index.js#L65) to support `ExportNamedDeclaration` and `ExportAllDeclaration`.

**Comment by olalonde** [comment]
Sent a PR

**Comment by michaelzoidl** [comment]
close, thx :)
