### ISSUE TITLE
root path ?

### ISSUE THREAD

**Issue by FredericHeem** [michaelzoidl/babel-root-import#4]
`babel-root-import` works fine when used with `babel-node` or with `mocha`.
Most projects have the source in `src` and the compiled Javascript in `build`, 
Is there a way to set the root path to `src` ? 
Otherwise, it doesn't work when the import is in the form of:
`import blabla from "~/src/blabla";`
because the file `~/src/blabla` is in es6 whereas it should use `~/build/blabla`

**Comment by michaelzoidl** [comment]
Thanks for the idea and the solution.
Your PR is merged :)

**Comment by michaelzoidl** [comment]
Ah.. one thing
we should update the Readme, i let this ticket open still the readme is adapted

**Comment by michaelzoidl** [comment]
:( bad news... i had to remove this feature while i updated the `babel-root-import` to the new babel-plugin-api (`6.XX.X`).
They have not implemented a custom / extra params thing for the `.babelrc`.

Hope they implement this soon... 

In your case: just don't update to the new `3.0.0` version of the importer..

**Comment by billyjanitsch** [comment]
@michaelzoidl I believe plugins can take options in Babel 6 with a slightly different API: https://babeljs.io/docs/plugins/#options

**Comment by danez** [comment]
I just wanted to suggest the same thing and as @billyjanitsch already mentioned it should be possible.

**Comment by michaelzoidl** [comment]
Okay guys... this feature is now (from version `3.1.0`) implemented! Thanks to @degr.
