### ISSUE TITLE
Parse paths aside from imports like `jest.unmock('~/some/file')`

### ISSUE THREAD

**Issue by maikokuppe** [michaelzoidl/babel-root-import#41]
When using jest tests, I often get a case like this:
```
jest.unmock('../../../classes/feed.js');
import Feed from '~/classes/feed';
```
I can use the nice project-relative path in the import statements, but not in the unmock paths.
I think this is not specifically related to a jest usecase, but rather a general issue.

Is it possible to include some functionality that allows the use of '~/...' in such cases? Maybe something like `jest.unmock(pathToRoot('~/classes/feed.js'))`?

**Comment by michaelzoidl** [comment]
Hm.. if it's okay to use every time the `pathToRoot` function you can just create some function which replaces the `~` with the basic path.

You could use the [plugin/helper.js](https://github.com/michaelzoidl/babel-root-import/blob/master/plugin/helper.js#L22-L38) functions.. :)

**Comment by maikokuppe** [comment]
Thanks, I'm gonna try that. Closing this for now, assuming it's going to help me ;)
