### ISSUE TITLE
4.1.0 on NPM doesn't seem to be the right version

### ISSUE THREAD

**Issue by JeffreyATW** [michaelzoidl/babel-root-import#45]
I'm trying to upgrade to 4.1.0 to get the relative import functionality but the version published to NPM doesn't seem correct. If you download the [tarball](https://registry.npmjs.org/babel-root-import/-/babel-root-import-4.1.0.tgz), you'll see that the `build` folder is out of date. Can you try republishing?

**Comment by michaelzoidl** [comment]
Yo @JeffreyATW thank you for investigating in this.
I was in vacation the last weeks..

Maybe you've seen already i released yesterday the `4.1.1` where i compiled the code...
