### ISSUE TITLE
package is not updated in npm

### ISSUE THREAD

**Issue by nescalante** [michaelzoidl/babel-root-import#50]
Hey, I just realized it 20 days after the merge, but you never did `npm run compile` before doing the publish to npm so the code is not updated there.
Can you please do `npm run compile` and then re-publish a new patch?

Thanks in advance.

**Comment by michaelzoidl** [comment]
Hi @nescalante sorry for the delay (got your mail yesterday)
I rebuild everything and released a new version on npm (4.1.2)

Hope everything works again.

Michael

**Comment by michaelzoidl** [comment]
Ok since i merged the new PR the new version is `4.1.3` :)

Since this is done now i close this - thanks for the call

**Comment by nescalante** [comment]
😄 👍
