### ISSUE TITLE
Define where the root is

### ISSUE THREAD

**Issue by si-mikey** [michaelzoidl/babel-root-import#51]
How do I tell this module where the root is?

**Comment by sivael** [comment]
It looks like the root is where you run npm install.

**Comment by si-mikey** [comment]
the thing is that it doesn't properly add the root to the transpiled files, 
files are in  ../../dist/ and after transpiling its just ../dist/

**Comment by sivael** [comment]
I've worked on a few projects and it didn't have issues here. Could You give me a link to the repo so that I can look at it?

**Comment by michaelzoidl** [comment]
The root is the path behind `process.cwd()` thats the current-working-dir, so so you could say where the package.json is.. 

Can you give us more details about your setup? node, babel, babel-root-import versions..

**Comment by michaelzoidl** [comment]
since there is no answer: /close
