### ISSUE TITLE
Expect to support the @import rule in css 

### ISSUE THREAD

**Issue by shikelong** [michaelzoidl/babel-root-import#52]
Regards.

**Comment by michaelzoidl** [comment]
If you're using webpack you could use the [import-glob-loader](https://www.npmjs.com/package/import-glob-loader) module, then make a `app.scss` and import every scss file via `@import ./style/**/*.scss` that's how i'm avoiding import a million times files.. 

But if you want this stuff you could use (also with webpack) the alias options, there you could setup something like:
```
alias: {
  '~': process.cwd() + '/src/style'
}
```

After that you can simple import stuff with `@import ~/foo/bar.scss` 

If we embed this option in the module, maybe in a later version, but for now we focus on supporting the import/require functions only for JS :)

**Comment by shikelong** [comment]
Thank you.
