### ISSUE TITLE
Flow support

### ISSUE THREAD

**Issue by cajacko** [michaelzoidl/babel-root-import#58]
Hi,

Great plugin, really handy.

I'm having some issues getting flow to play nice though with the specified name_mapper regex.

Here's my .flowconfig

    [ignore]
    .*/node_modules

    [include]

    [libs]

    [options]
    module.name_mapper='^~\/\(.*\)$' -> '<PROJECT_ROOT>/\1'

And here is a file that flow is checking:

    import * as types from '~/actions/actionTypes.js';

This is the flow error:

    import * as types from '~/actions/actionTypes.js';
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^ ~/actions/actionTypes.js. Required module not found

**Comment by michaelzoidl** [comment]
Phew, i'm not using flow but the error make sense since all linters etc mark this syntax as "error".
I'm not familiar with flow so i think i cannot help you with this since it's no issue from the babel-plugin, try to make an issue on the flow project :) they should how to add some kind of rule to allow this syntax.

**Comment by cajacko** [comment]
Ah, I just mentioned it here as you explicitly talk about it in your documentation, and I implemented the exact code but it does not work. Below is the extract from your documentation, maybe it should be updated if it no longer applies?:

------

Don't let Flow be confused

If you use Facebook's Flow for type-checking it is necessary to instruct it on how to map your chosen prefix to the root directory. Add the following to your .flowconfig file, replacing ~ with your chosen prefix.
```

[options]
module.name_mapper='^~\/\(.*\)$' -> '<PROJECT_ROOT>/\1'

```

**Comment by michaelzoidl** [comment]
Oh well, you're right, seem's like flow has a new version which doesn't support this anymore.
Do you know what the last version was which supported this? Then i would say we should note that in the readme.

And how do you use it now? Do you have some kind of work-around or just stopped using this plugin?

**Comment by chriskurzeja** [comment]
Just to drop in my two cents. I've had this working with flow 0.35.0. 

In my project I'm using '~/' to map to '<PROJECT_ROOT>/gulp/javascript/'. So in the config I ended up specifying:

`
[options]
module.name_mapper='^~/\(.*\)$' -> '<PROJECT_ROOT>/gulp/javascripts/\1'
`

Note that I dropped the first escape character ( '/' didn't need an escape) and made sure that I had added the rootPathSuffix from my .babelrc into the mapping before I'd then included the group. Perhaps a rewrite of the documentation to clarify along the lines of:

> Don't let Flow be confused
> 
> If you use Facebook's Flow for type-checking it is necessary to instruct it on how to map your chosen prefix to the root directory. Add the following to your .flowconfig file, replacing ~ with your chosen prefix and ensure that the mapping includes the corresponding suffix
> 
> 
> [options]
> module.name_mapper='^**{pathPrefix}**/\\(.*\\)$' -> '<PROJECT_ROOT>**{insert pathSuffix for prefix}**/\1'

**Comment by web2style** [comment]
@michaelzoidl Please, update the README with @chriskurzeja's solution not to confuse the users. It works.

**Comment by michaelzoidl** [comment]
Thanks for contribution :) i will merge it..
