### ISSUE TITLE
Support for Visual Studio Code?

### ISSUE THREAD

**Issue by mwlpeeters** [michaelzoidl/babel-root-import#61]
I've added the babel-root-import to my project but now the intellisence of Visual Studio Code is no longer resolving the imports correctly.
Any idea/experience in fixing this?

**Comment by michaelzoidl** [comment]
Hm.. and using another editor / IDE fixes this problem?

**Comment by mwlpeeters** [comment]
Just tried WebStorm but that IDE makes me cry even more

**Comment by michaelzoidl** [comment]
Hm.. how do you start babel? I mean.. if you run something like `node_modules/.bin/babel-node youfile.js` in your terminal it should start correctly.. 
You defined everything in the `.babelrc`, right? (or you passed the plugin as flag in the cli command)

**Comment by mwlpeeters** [comment]
I'm using an ejected react app that I created with create-react-app. Added the `.babelrc` to the project but it does not seem te be picked up. Probably because the complete configuration has been put in several scripts.

In my `package.json` I added the `babel-root-import`:

  "babel": {
    "presets": [
      "react-app"
    ],
	  "plugins": [
		  ["babel-root-import", {
			  "rootPathPrefix": "~",
			  "rootPathSuffix": "src"
		}]
	  ]
  },

This seems to work because when I change ~ in @, compilation will fail until I change the imports to start with a @ instead of a ~.

**Comment by mwlpeeters** [comment]
I'm giving up on Visual Studio Code, thanks for helping finding a solution

**Comment by michaelzoidl** [comment]
Okay, 😂 try using atom or sublime, they're awesome

**Comment by SuhairZain** [comment]
@mwlpeeters Were you able to get ~ imports working with VS Code IntelliSense? Could you share the solution if you have?

**Comment by SuhairZain** [comment]
Actually, I've found a solution at https://github.com/Microsoft/vscode/issues/14907#issuecomment-271462011 if anyone's inclined to use VS Code. 😄

**Comment by arastu** [comment]
this solution works for me

```
// jsconfig.json
{
    "compilerOptions": {
        "target": "ES6",
        "module": "commonjs",
        "allowSyntheticDefaultImports": true,
        "baseUrl": "./",
        "paths": {
          "~/*": ["./*"]
        }
    },
    "exclude": [
        "build",
        "node_modules",
        "static"
    ]
}
```

**Comment by kevbost** [comment]
@arastu You deserve massive kudos for this solution.  I've wasted a ton of time trying to figure this out and this is the solution for intellisense click following import paths with a root of tilde `import wow from ~/utils/coolFile` with an actual path of `resources/assets/js/utils/coolFile.js`

**Comment by belicov-dmitrii** [comment]
It's worked for me: Try to add ./ before path to match the example
<img width="332" alt="Screen Shot 2020-12-15 at 11 03 44 AM" src="https://user-images.githubusercontent.com/36342619/102193799-34306b80-3ec5-11eb-8215-41459c01c01d.png">
