### ISSUE TITLE
configuration

### ISSUE THREAD

**Issue by degr** [michaelzoidl/babel-root-import#7]
Hello, I can't understand, how I can configure this plugin. Just for now, I found only one way - create new npm plugin with this index.js file:

>global.rootPath = process.cwd() + (global.srcRootPath ? '/' + global.srcRootPath.replace(/^(\/)|(\/)$/g, '') : '');
>module.exports = require('../babel-root-import/build/index.js');

in this case, I can set  global.srcRootPath variable in my gulpfile.js. Please, modify your code with this lines, or please say, how I can do this customization. Many thanks.

**Comment by michaelzoidl** [comment]
In my case it wasn't necessary - but you're right.. this is a interesting feature and a few guys already asked for this.

Your solution is good, but if we implement a feature which supports the custom-root config it should be defined in the `.babelrc`

We're already discussed in the #4 issue. (@billyjanitsch @danez)

Has anyone time to implement this feature? I think the next time i've time to dev this is in the christmas time :/ so 2-3 weeks.

**Comment by degr** [comment]
I do pull request for today. But, unfortunately, I don't know how to transform 'plugin' directory into 'build'  directory. I test this in 'build', and all work perfectly. Please, check how it will work with with 'build' after es6 transformations.

**Comment by michaelzoidl** [comment]
Ok cool - make some PR then we can discover this issue :)
Do you've already implemented some tests? (i think it's possible - when you've used the `.babelrc` API)

Thanks!

**Comment by degr** [comment]
mauhahaha, this is my fault, I do PR in my repo (https://github.com/degr/babel-root-import/pulls). How I can do PR from my fork into your rep? And one more thing - you already have same functionality here - https://github.com/michaelzoidl/babel-root-import/pull/5 (in my case you use plugin options, in that case you use babel -extra

**Comment by michaelzoidl** [comment]
lol, ya no problem :) you should find a green button ![](https://help.github.com/assets/images/help/pull_requests/pull-request-start-review-button.png)
Then you open a new PR here in this repo.. then you should see it on the Pull Requests Tab.

And ya, in the old PR it worked fine, but for the Babel 5.0 Version, they changed the API, i just saw how you pass extra params now:

```
{
  "plugins": [
    ["babel-root-import", {
      "root": "foo"
    }]
  ]
}
```

Do you've implemented the root feature with this API? (but just make a PR, then we can discuss there, in a PR you call always update files)

**Comment by michaelzoidl** [comment]
Okay guys... this feature is now (from version `3.1.0`) implemented! Thanks to @degr.
